### ISSUE TITLE
Island Duo Type Not work

### ISSUE THREAD

**Issue by NycuRO** [Nukkit-coders/ASkyBlock-Nukkit#2]
```java
16:04:47 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerFormRespondedEvent' to 'ASkyBlock v0.3.7-BETA': null on com.larryTheCoder.panels.Panel
16:04:47 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.handleDataPacket(Player.java:2408)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1979)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:473)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 12
        at cn.nukkit.block.BlockVine.onUpdate(BlockVine.java:178)
        at cn.nukkit.level.Level.updateAround(Level.java:1247)
        at cn.nukkit.level.Level.setBlock(Level.java:1688)
        at com.larryTheCoder.schematic.IslandBlock.revert(IslandBlock.java:491)
        at com.larryTheCoder.schematic.SchematicHandler.pasteSchematic(SchematicHandler.java:531)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:204)
        at com.larryTheCoder.panels.Panel.onPlayerRespondForm(Panel.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more
```

**Comment by NycuRO** [comment]
#3
