### ISSUE TITLE
Bugs of ASkyblock-Nukkit

### ISSUE THREAD

**Issue by NycuRO** [Nukkit-coders/ASkyBlock-Nukkit#3]
**List of Bugs:**

1. [ ] Shit blocks appereal on Schematic when is replaced. (Not all times). Need re-create schematics.
Confirmed: Reproduced when try create "Island Duo" and before "Original Type": https://i.imgur.com/2dy653E.png
2. [x] [cmd] on message wasn't replaced: 
Confirmed: Reproduced when use /is delete:
https://i.imgur.com/LzGUnR7.png
3. [x] You can't get items from "Default Original" Type.
Confirmed: Create island "Default Original" Type and try get items from chest:
https://i.imgur.com/6YtERsa.png
4. [x] Chest not appereal on type "Black Diamonds".
Non Confirmed: Idk how reproduce.
5. [ ] Type "Island Duo" not work. (This is reproduce #1 , because it's by schematic outdated ).
6. [x] If you try use /is delete in default world, without /is setspawn, get same messages:
Confirmed!
https://i.imgur.com/MHuy7Yx.jpg
7. [ ] When you create first time Island, get this bug (not every time):
```java
16:31:50 [INFO] [ASkyBlock] NycuR0 data doesn`t exsits. Creating new ones
16:31:50 [INFO] NycuR0 joined the game
16:32:06 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$ValueIterator.next(Unknown Source)
        at cn.nukkit.level.Level.setChunk(Level.java:2373)
        at cn.nukkit.level.Level.generateChunkCallback(Level.java:2316)
        at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
        at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
        at cn.nukkit.Server.tick(Server.java:1012)
        at cn.nukkit.Server.tickProcessor(Server.java:807)
        at cn.nukkit.Server.start(Server.java:786)
        at cn.nukkit.Server.<init>(Server.java:473)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
```
8. [x] /is setspawn is really /isa setspawn, fix worng instructions
9. [x] Setting chest items in config not work
10. [x] When I type /is delete not in SkyBlock world it says "You cannot do that in this world." but still deletes the island
11. [x] Fix build-in island generator
12. [ ] This plugin not work with NukkitX

**Comment by PetteriM1** [comment]
- For me chest appereal on Black Diamonds
- Setting chest items in config not work
- When I type /is delete not in SkyBlock world it says "You cannot do that in this world." but still deletes the island
- Suggestion: Clear player inventory when he deletes his island
- Suggestion: Remove that empty sign generation
- /is setspawn is really /isa setspawn, fix worng instructions
- Question: Which program is used to make these schematics?

**Comment by PetteriM1** [comment]
Last working version here: https://github.com/TheSolidCrafter/ASkyBlock-Nukkit
