### ISSUE TITLE
Could not load other schematics

### ISSUE THREAD

**Issue by UnexMC** [Nukkit-coders/ASkyBlock-Nukkit#5]
06:46:41 [INFO] [ASkyBlock] Enabling ASkyBlock - Founders Edition (API 21)
06:46:41 [INFO] [ASkyBlock] Loading offline messages...
06:46:41 [INFO] [ASkyBlock] Loading the Island Framework
06:46:41 [INFO] [ASkyBlock] Starting Schematic Resource Pack.
06:46:41 [INFO] [ASkyBlock] Loading schematic framework
06:46:41 [ALERT] java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:631)
        at cn.nukkit.Server.enablePlugins(Server.java:620)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.NullPointerException
        at com.larryTheCoder.schematic.SchematicHandler.handleSchematic(SchematicHandler.java:468)
        at com.larryTheCoder.schematic.SchematicHandler.<init>(SchematicHandler.java:440)
        at com.larryTheCoder.ASkyBlock.loadV2Schematic(ASkyBlock.java:438)
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:332)
        at com.larryTheCoder.ASkyBlock.start(ASkyBlock.java:253)
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:237)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 4 more

**Comment by UnexPE** [comment]
huch

**Comment by PetteriM1** [comment]
Can you please send schematic file what you try to load?

**Comment by PetteriM1** [comment]
Last working version here: https://github.com/TheSolidCrafter/ASkyBlock-Nukkit
